services:
  # --- USER SERVICE ---
  user-db:
    image: postgres:15
    container_name: user-db
    env_file:
      - ./user-service/.env
    restart: always
    ports:
      - "5433:5432"
    networks:
      - uitgo-net
    volumes:
      - user-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-service:
    build: ./user-service
    container_name: user-service
    env_file:
      - ./user-service/.env
    ports:
      - "8081:8081"
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - uitgo-net

  # --- DRIVER SERVICE ---
  driver-db:
    image: postgres:15
    container_name: driver-db
    env_file:
      - ./driver-service/.env
    restart: always
    ports:
      - "5434:5432"
    networks:
      - uitgo-net
    volumes:
      - driver-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  driver-redis:
    image: redis:7
    container_name: driver-redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - uitgo-net

  driver-service:
    build: ./driver-service
    container_name: driver-service
    env_file:
      - ./driver-service/.env
    ports:
      - "8082:8082"
    depends_on:
      driver-db:
        condition: service_healthy
      driver-redis:
        condition: service_started
    networks:
      - uitgo-net

  # --- TRIP SERVICE ---
  trip-db:
    image: postgres:15
    container_name: trip-db
    env_file:
      - ./trip-service/.env
    restart: always
    ports:
      - "5435:5432"
    networks:
      - uitgo-net
    volumes:
      - trip-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  trip-service:
    build: ./trip-service
    container_name: trip-service
    env_file:
      - ./trip-service/.env
    ports:
      - "8083:8083"
    depends_on:
      trip-db:
        condition: service_healthy
      user-service:
        condition: service_started
      driver-service:
        condition: service_started
    networks:
      - uitgo-net

# --- NETWORKS & VOLUMES ---
networks:
  uitgo-net:
    driver: bridge

volumes:
  user-data:
  driver-data:
  trip-data:
